name: Trigger Update in Repository A

on:
  push:
    branches:
      - main

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger repository_dispatch event in Repository nexa
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: samgec123/submodule-nexa
          event-type: commons-updated
